문제 1

In [21]:
import numpy as np
num_arr = np.arange(1, 21)
print(num_arr)
print(num_arr[::-1]) # np.flip(num_arr)
print('num_arr 내의 모든 원소의 합 :', sum(num_arr))
print(num_arr.reshape(5,4))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]
num_arr 내의 모든 원소의 합 : 210
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


문제 2

In [72]:
n_arr = np.arange(0 , 25)
a = n_arr.reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [74]:
print('첫 원소 :', a[0, 0])
print('마지막 원소 :', a[-1, -1])

첫 원소 : 0
마지막 원소 : 24


In [78]:
a[0:2,:]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [82]:
a[2:,:]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

문제 3

In [90]:
a = np.random.rand(3,3,3)
a

array([[[0.33769905, 0.12724056, 0.25545703],
        [0.35054924, 0.64982237, 0.78590442],
        [0.74914081, 0.12660008, 0.9220187 ]],

       [[0.38541063, 0.44338894, 0.56175542],
        [0.59515299, 0.12277043, 0.65037531],
        [0.79706705, 0.55067777, 0.03293994]],

       [[0.19820907, 0.42793742, 0.05494331],
        [0.21326991, 0.46694683, 0.71148699],
        [0.96341047, 0.63391717, 0.06947389]]])

In [91]:
print('a의 원소들 중 최대값 :', a.max())

a의 원소들 중 최대값 : 0.9634104697317718


In [92]:
print('a의 원소들 중 최대값 :', a.argmax())

a의 원소들 중 최대값 : 24
